title = "Angelo Blades"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Philadelphia, PA"
email = "angelo.blades@gmail.com"
favicon = "/favicon.ico"
firstName = "Angelo"
lastName = "Blades"
phone = "570 446 8162"
profileImage = "img/me.jpeg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["skills","experience","education"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]
[[params.handles]]
  name = "LinkedIn"
  link = "https://www.linkedin.com/in/angelo-blades-76b921140"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true